name: Run Dependency Scan
on:
  pull_request:
     branches:
      - main  
      - master
      - dev
      - release
      - develop
      - mainline
  push:
    branches:
      - main  
      - master
      - dev
      - release
      - develop
      - mainline
  workflow_dispatch:

jobs:
  call-dependency-scan:
    uses: zeptonow/workflow-hub/.github/workflows/sca.yaml@main
    secrets: inherit